### ISSUE TITLE
Error when running plottree

### ISSUE THREAD

**Issue by Shellfishgene** [iBiology/plottree#1]
Hi!
When I try plottree I get this error:
```
> plottree 
Traceback (most recent call last):
  File "/usr/local/bin/plottree", line 7, in <module>
    from plottree.plottree import main
  File "/usr/local/lib/python3.5/dist-packages/plottree/plottree.py", line 56
    settings.append(f'fontsize (-s): {size:.1f}')
                                               ^
```

**Comment by iBiology** [comment]
Are you using python 2? Please try python 3 instead. If it still doesn't
work, please send me the full error message.


*FEI YUAN*, Ph. D
Bioinformatics Programmer
Houston, TX, 77021

**Comment by Shellfishgene** [comment]
Mixed up my Python versions, works with 3.6. The Q&A still says it works with 2 though. Thanks!
